### ISSUE TITLE
Cannot initialize a parameter of type 'id<NSCopying> _Nonnull' with an rvalue of type 'Class' 

### ISSUE THREAD

**Issue by luckyhong** [rwbutler/FeatureFlags#3]
![image](https://user-images.githubusercontent.com/12805890/116513218-d04e9280-a8fb-11eb-9d2e-a48f63844e3d.png)

How to fix it in Xcode12.5?

**Comment by luckyhong** [comment]
I downloaded Xcode 12.5 and now an FBClassStrongLayout.mm does not compile with errors telling I can't use Class as a key in NSDictionary?

Can it be changed like this？
layoutCache[(id)currentClass] = ivars;

**Comment by rwbutler** [comment]
Apologies, however this doesn't appear to be related to the FeatureFlags library?

**Comment by luckyhong** [comment]
I'm so sorry. you're right.😁

**Comment by luckyhong** [comment]
> Apologies, however this doesn't appear to be related to the FeatureFlags library?

I'm so sorry. you're right.😁
