### ISSUE TITLE
Push version 2.6.3 to the spec repo

### ISSUE THREAD

**Issue by colinhumber** [rwbutler/FeatureFlags#4]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'm unable to directly install version 2.6.3 from my Podfile since it hasn't been pushed to the spec repo yet, though the tag has been created in the project repo.

**Describe alternatives you've considered**
I can directly reference the repo when installing the version if need be.

**Additional context**
N/A

**Comment by rwbutler** [comment]
Hi @colinhumber apologies I'll look to resolve this later today.

**Comment by rwbutler** [comment]
@colinhumber  2.6.4 is now published https://github.com/rwbutler/FeatureFlags/releases/tag/2.6.4
