### ISSUE TITLE
Allow usage of UI components when importing with SPM

### ISSUE THREAD

**Issue by colinhumber** [rwbutler/FeatureFlags#5]
**Is your feature request related to a problem? Please describe.**
I'm unable to use the `FeatureFlagsViewController` or associated UI classes when importing the framework via SPM. It looks like all the classes in the UI folder are being excluded, from what I can tell in the package file.

**Describe the solution you'd like**
I'd like to be able to use the UI classes when importing via SPM.

**Describe alternatives you've considered**
Use Cocoapods to import.

**Additional context**
N/A

**Comment by rwbutler** [comment]
Hi @colinhumber thanks for flagging - when I initially added the `Package.swift` to the project iOS wasn't supported by SPM therefore UIKit was unavailable. iOS has been supported by SPM for a long time now so there's no reason why the view controller can't be made available - I'll look to change this.

**Comment by rwbutler** [comment]
@colinhumber Available now in 2.6.4 https://github.com/rwbutler/FeatureFlags/releases/tag/2.6.4
